---
# tasks file for pbm
- name: install GPG key for epel 8
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: install GPG key for Percona repos
  rpm_key:
    state: present
    key: https://repo.percona.com/yum/RPM-GPG-KEY-Percona
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: include tasks for test env setup
  include_tasks: ../../../tasks/test_prep.yml

- name: Install percona repository package
  apt:
    deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
  when: ansible_os_family == "Debian"

- name: add the Percona testing yum repos for centos 6 and 7
  yum: name=https://repo.percona.com/yum/percona-release-latest.noarch.rpm
  when: ansible_os_family == "RedHat"

- name: clean and update yum cache
  shell: |
    yum clean all
    yum makecache
  when: ansible_os_family == "RedHat"

- name: setup psmdb repo with percona-release
  command: percona-release enable {{ psmdb_to_test }} {{ install_repo }}
  vars:
    install_repo: "{{ lookup('env', 'install_repo') }}"
    psmdb_to_test: "{{ lookup('env', 'psmdb_to_test') }}"
  when: lookup('env', 'install_repo') == "testing"

- name: setup psmdb repo with percona-release
  command: percona-release enable {{ psmdb_to_test }}
  vars:
    psmdb_to_test: "{{ lookup('env', 'psmdb_to_test') }}"
  when: lookup('env', 'install_repo') == "main"

- name: setup pbm repo with percona-release
  command: percona-release enable pbm {{ install_repo }}
  vars:
    install_repo: "{{ lookup('env', 'install_repo') }}"
  when: lookup('env', 'install_repo') == "testing"

- name: setup pbm repo with percona-release
  command: percona-release enable pbm
  vars:
    install_repo: "{{ lookup('env', 'install_repo') }}"
  when: lookup('env', 'install_repo') == "main"

- name: include tasks for PSMDB 4.0 and 4.2 install
  include_tasks: install_psmdb_full.yml
  when: lookup('env', 'psmdb_to_test') == "psmdb-40" or lookup('env', 'psmdb_to_test') == "psmdb-42" or lookup('env', 'psmdb_to_test') == "psmdb-44"

- name: include tasks for PSMDB 3.6 install
  include_tasks: install_psmdb_36_full.yml
  when: lookup('env', 'psmdb_to_test') == "psmdb-36"

- name: stop mongod service
  service: name=mongod state=stopped

- name: add replica set name into mongod config
  replace:
    path: /etc/mongod.conf
    regexp: '^#replication:'
    replace: 'replication:\n  replSetName: "rs1"'

- name: start mongod service
  service: name=mongod state=started

- name: initiate mongod replica set
  command: mongo --eval 'rs.initiate()'

- name: install PBM new deb packages
  apt:
    name: percona-backup-mongodb={{ version }}
    update_cache: yes
    state: latest
  vars:
    version: "{{ lookup('env', 'FROM_VERSION') }}"
  when: ansible_os_family == "Debian"

- name: install PBM new rpm packages
  yum:
    name: percona-backup-mongodb-{{ version }}
    state: latest
  vars:
    version: "{{ lookup('env', 'FROM_VERSION') }}"
  when: ansible_os_family == "RedHat"

- name: add storage for pbm-agent
  blockinfile:
    path: /etc/pbm-agent-storage.conf
    mode: '0666'
    create: true
    block: |
      storage:
        type: s3
        s3:
           region: us-east-1
           bucket: operator-testing
           credentials:
             access-key-id: {{ access_key }}
             secret-access-key: {{ access_secret }}
  vars:
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    access_secret: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

- name: add GCP storage for pbm-agent
  blockinfile:
    path: /etc/pbm-agent-storage-gcp.conf
    mode: '0666'
    create: true
    block: |
      storage:
        type: s3
        s3:
           region: us-east-1
           endpointUrl: https://storage.googleapis.com
           bucket: operator-testing
           credentials:
             access-key-id: {{ access_key }}
             secret-access-key: {{ access_secret }}
  vars:
    access_key: "{{ lookup('env', 'GCP_ACCESS_KEY') }}"
    access_secret: "{{ lookup('env', 'GCP_SECRET_KEY') }}"

- name: add local storage for pbm-agent
  blockinfile:
    path: /etc/pbm-agent-storage-local.conf
    mode: '0666'
    create: true
    block: |
      storage:
          type: filesystem
          filesystem:
              path: /tmp

- name: edit pbm-agent service config for deb
  blockinfile:
    path: /etc/default/pbm-agent
    block: |
      PBM_MONGODB_URI="mongodb://localhost:27017/"
  when: ansible_os_family == "Debian"

- name: edit pbm-agent service config for rhel based
  blockinfile:
    path: /etc/sysconfig/pbm-agent
    block: |
      PBM_MONGODB_URI="mongodb://localhost:27017/"
  when: ansible_os_family == "RedHat"

- name: start pbm-agent service
  service:
    name: pbm-agent
    state: started
    enabled: yes
