---
# Tasks for test minor upgrade for PPG 11 packages

- name: Configure repository
  include_tasks: ../../../tasks/install_percona_release.yml

- name: Setup initial (old) repository
  command: percona-release enable {{ pg_version }} {{ repo }}
  vars:
    repo: "{{ lookup('env', 'FROM_REPO') }}"
    pg_version: "{{ lookup('env', 'FROM_VERSION') }}"

- name: install Percona Platform for PostgreSQL 11 packages
  include_tasks: ../../../../tasks/install_ppg11.yml

- name: Initialize Postgres RHEL
  command: /usr/pgsql-11/bin/postgresql-11-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Install PPG tools
  include_tasks: ../../common/tasks/install_ppg11_tools.yml

- name: Start Postgres RHEL
  service:
    name: postgresql-11
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Enable and start postgresql service for RHEL based
  service:
    name: postgresql-11
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Enable and start postgresql service for Debian based
  service:
    name: postgresql
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"


- name: Stop postgresql service for RHEL based
  service:
    name: postgresql-11
    state: stopped
  when: ansible_os_family == "RedHat"

- name: Stop postgresql service for Debian based
  service:
    name: postgresql
    state: stopped
  when: ansible_os_family == "Debian"

- name: Disable old repository
  command: percona-release disable {{ pg_version }} {{ repo }}
  vars:
    repo: "{{ lookup('env', 'FROM_REPO') }}"
    pg_version: "{{ lookup('env', 'FROM_VERSION') }}"

- name: Setup new repository
  command: percona-release enable {{ pg_version }} {{ repo }}
  vars:
    repo: "{{ lookup('env', 'TO_REPO') }}"
    pg_version: "{{ lookup('env', 'VERSION') }}"

- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Percona Platform for PostgreSQL 11 packages
  include_tasks: ../../../../tasks/install_ppg11.yml

- name: Start postgresql service for RHEL based
  service:
    name: postgresql-11
    state: started
  when: ansible_os_family == "RedHat"

- name: Install PPG tools
  include_tasks: ../../common/tasks/install_ppg11_tools.yml


- name: Start postgresql service for Debian based
  service:
    name: postgresql
    state: started
  when: ansible_os_family == "Debian"

- name: Install GCC Deb
  apt:
    name: gcc
  when: ansible_os_family == "Debian"

- name: Install GCC RHEL
  yum:
    name: gcc
  when: ansible_os_family == "RedHat"

- name: Create temporary directory for compilation
  command: mkdir /tmp/libpq_command_temp_dir

- name: Copy libpq source file
  copy:
    src: ../../common/files/lib_version.c
    dest: /tmp/libpq_command_temp_dir
