
  - name: include playbook for removing Percona repo
    include: remove_percona_repository.yml

  - name: add an apt signing key
    apt_key: id=8507EFA5 keyserver=keys.gnupg.net state=present
    when: ansible_os_family == "Debian"

  - name: add the old apt signing key
    apt_key: id=CD2EFD2A keyserver=keys.gnupg.net state=present
    when: ansible_os_family == "Debian"

  - name: add the main Percona deb repo
    apt_repository: repo='deb http://repo.percona.com/apt {{ ansible_lsb.codename }} main' state=present update_cache=yes
    when: ansible_os_family == "Debian"

  - name: add the main Percona yum repos for centos 5
    command: "{{ item }}"
    with_items:
      - wget -P ~ https://www.percona.com/redir/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm
      - rpm -ivH ~/percona-release-0.1-4.noarch.rpm
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

  - name: add the main Percona yum repos for centos 6 and 7
    yum: name=https://www.percona.com/redir/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version != "5"
