  - name: include playbook for removing Percona repo
    include: remove_percona_repository.yml

  - name: Install percona repository package
    apt:
      deb: https://repo.percona.com/apt/percona-release_0.1-10.{{ansible_lsb.codename}}_all.deb
    when: ansible_os_family == "Debian"

  - name: add the Percona testing yum repos for centos 6 and 7
    yum: name=https://repo.percona.com/yum/testing/7Server/RPMS/noarch/percona-release-1.0-9.noarch.rpm
    when: ansible_os_family == "RedHat" 

  - name: enable the PSMDB experimental repo
    command: percona-release enable-only psmdb-40 experimental
