  - name: include playbook for removing Percona repo
    include_tasks: remove_percona_repository.yml

  - name: disable the mysql module on RHEL/CentOS 8
    command: /usr/bin/dnf module disable mysql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Install percona repository package
    apt:
      deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    when: ansible_os_family == "Debian"

  - name: add the Percona testing yum repos for centos 6 and 7
    yum: name=https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    when: ansible_os_family == "RedHat"

  - name: enable the PS-8X  Innovation main repo
    command: percona-release enable-only ps-8x-innovation release

  - name: enable the tools main repo
    command: percona-release enable tools release

  - name: clean and update yum cache
    shell: |
      yum clean all
      yum makecache
    when: ansible_os_family == "RedHat"
