  - name: include playbook for removing Percona repo
    include_tasks: remove_percona_repository.yml

  - name: disable the mysql module on RHEL/CentOS 8
    command: /usr/bin/dnf module disable mysql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

#  - name: Receive GPG key 1
#    command: "gpg --batch --keyserver keyserver.ubuntu.com --recv-keys {{ percona_key1 }}"
#    environment:
#      GNUPGHOME: "{{ gnupg_home }}"
#    when: ansible_os_family == "RedHat"

#  - name: Export GPG key 1
#    command: "gpg --batch --export --armor {{ percona_key1 }}"
#    register: gpg_key1
#    environment:
#      GNUPGHOME: "{{ gnupg_home }}"
#    when: ansible_os_family == "RedHat"

 # - name: Save GPG key 1 to file
 #   copy:
 #     content: "{{ gpg_key1.stdout }}"
 #     dest: "{{ percona_key1_file }}"
 #     mode: '0644'
 #   when: ansible_os_family == "RedHat"

#  - name: Import GPG keys with rpmkeys
#    command: "rpmkeys --import {{ percona_key1_file }}"
#    when: ansible_os_family == "RedHat"

  - name: Install percona repository package
    apt:
      deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    when: ansible_os_family == "Debian"

  - name: Add the Percona Release yum repo without GPG check
    yum:
      name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
      disable_gpg_check: yes
    when: ansible_os_family == "RedHat"

  - name: enable the PS-84 main repo
    command: percona-release enable-only ps-8x-innovation release

  - name: enable the pxb-84 release repo
    command: percona-release enable pxb-8x-innovation release

# - name: enable the tools main repo
#   command: percona-release enable tools release

  - name: clean and update yum cache
    shell: |
      yum clean all
      yum makecache
    when: ansible_os_family == "RedHat"
