  - name: include playbook for removing Percona repo
    include_tasks: remove_percona_repository.yml

  - name: disable the mysql module on RHEL/CentOS 8
    command: /usr/bin/dnf module disable mysql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Install percona repository package
    apt:
      deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    when: ansible_os_family == "Debian"

  - name: Add the Percona Release yum repo without GPG check
    yum:
      name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
      disable_gpg_check: yes
    when: ansible_os_family == "RedHat"

  - name: enable main repo pxc-80
    command: percona-release enable-only pxc-80 release

  - name: enable pxb repo
    command: percona-release enable pxb-80 release
    when:
      - ansible_distribution != "Amazon"

  - name: add the main tools repo
    command: percona-release enable tools release
    when:
      - ansible_distribution != "Amazon"

  - name: Clean and update package cache
    shell: |
      {{ ansible_pkg_mgr }} clean all
      {{ ansible_pkg_mgr }} makecache
    when:
      - ansible_facts['distribution'] in ["RedHat", "CentOS", "OracleLinux", "Amazon"]
