  - name: include playbook for removing Percona repo
    include_tasks: remove_percona_repository.yml

  - name: disable the mysql module on RHEL/CentOS 8
    command: /usr/bin/dnf module disable mysql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Install percona repository package
    apt:
      deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
#     deb: https://repo.percona.com/apt/pool/testing/p/percona-release/percona-release_1.0-21.generic_all.deb
    when: ansible_os_family == "Debian"

  - name: Add the Percona Release yum repo without GPG check
    yum:
      name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
      disable_gpg_check: yes
    when: ansible_os_family == "RedHat"

  - name: Add ARM support into percona-release
    shell: sed -i "s|x86_64|x86_64 aarch64|" /usr/bin/percona-release
    when: ansible_architecture == "aarch64" or ansible_architecture == "arm64"


  - name: check file dir
    shell: ls -la && pwd

  - name: Lit dir
    shell: ls -la && pwd

  - name: enable the PS-{{ major_release_version }} {{ ps_inn_lts_repo_name }} release repo
    command: percona-release enable-only {{ ps_inn_lts_repo_name }} release

  - name: enable the tools testing repo
    command: percona-release enable tools testing

  - name: clean and update yum cache
    shell: |
      yum clean all
      yum makecache
    when: ansible_os_family == "RedHat"
