  - name: include playbook for removing Percona repo
    include_tasks: remove_percona_repository.yml

  - name: disable the mysql module on RHEL/CentOS 8
    command: /usr/bin/dnf module disable mysql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Install percona repository package for Debain
    apt:
      deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    when: ansible_os_family == "Debian"

  - name: Ensure gnupg home exists (Amazon Linux)
    file:
      path: "{{ gnupg_home }}"
      state: directory
      mode: '0700'
    when:
      - ansible_os_family == "RedHat"

  - name: Download Percona GPG key from Percona's repo (Amazon Linux)
    get_url:
      url: https://repo.percona.com/yum/PERCONA-PACKAGING-KEY
      dest: "{{ percona_key1_file }}"
      mode: '0644'
    when: ansible_os_family == "RedHat"

  - name: Import GPG keys with rpmkeys
    command: "rpmkeys --import {{ percona_key1_file }}"
    when: ansible_os_family == "RedHat"

  - name: Install percona repository package for RHEL
    yum: name=https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    when: ansible_os_family == "RedHat"

  - name: enable the PS-80 testing repo
    command: percona-release enable-only ps-80 testing

  - name: enable the pxb-80 testing repo
    command: percona-release enable pxb-80 testing
    when:
      - ansible_distribution != "Amazon"

  - name: Clean and update package cache
    shell: |
      {{ ansible_pkg_mgr }} clean all
      {{ ansible_pkg_mgr }} makecache
    when:
      - ansible_facts['distribution'] in ["RedHat", "CentOS", "OracleLinux", "Amazon"]

  - name: Add ARM support into percona-release
    shell: sed -i "s|x86_64|x86_64 aarch64|" /usr/bin/percona-release
    when: ansible_architecture == "aarch64" or ansible_architecture == "arm64"
