
  - name: include playbook for removing Percona repo
    include: remove_percona_repository.yml

  - name: disable the mysql module on RHEL/CentOS 8
    command: /usr/bin/dnf module disable mysql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Install percona repository package
    apt:
#    deb: https://repo.percona.com/apt/pool/testing/p/percona-release/percona-release_1.0-21.generic_all.deb
     deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    when: ansible_os_family == "Debian"

  - name: add the main Percona yum repos for centos 6 and 7
#   yum: name=https://repo.percona.com/yum/testing/latest/RPMS/noarch/percona-release-1.0-21.noarch.rpm
    yum: name=https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    when: ansible_os_family == "RedHat"

  - name: enable original main repo
    command: percona-release enable original release
    when: lookup('env', 'pxc57repo') == "original"

  - name: enable pxc-57 main repo
    command: percona-release enable-only pxc-57 release
    when: lookup('env', 'pxc57repo') == "pxc57"

# leaving for backward compitability before implementing original and pxc57 selection
  - name: enable main repo
    command: percona-release enable pxc-57 release
    when: lookup('env', 'pxc57repo') == ""

  - name: enable pxb24 repo
    command: percona-release enable pxb-24 release
    when: lookup('env', 'pxc57repo') == "pxc57" or lookup('env', 'pxc57repo') == ""

  - name: clean and update yum cache
    shell: |
      yum clean all
      yum makecache
    when: ansible_os_family == "RedHat"
