---
  - name: copy the global manifest for mysql
    copy:
        src: /package-testing/keyring-vault/mysqld.my
        dest: /usr/sbin/
        remote_src: yes

  - name: copy the global configuration file for mysql in Redhat/CentOS
    copy:
        src: /package-testing/scripts/ps_keyring_plugins_test/component_keyring_vault.cnf
        dest: /usr/lib64/mysql/plugin/
        remote_src: yes
    when: ansible_os_family == "RedHat"

  - name: copy the global configuration file for mysql in Debian/Ubuntu
    copy:
        src: /package-testing/scripts/ps_keyring_plugins_test/component_keyring_vault.cnf
        dest: /usr/lib/mysql/plugin/
        remote_src: yes
    when: ansible_os_family == "Debian"

  - name: keyring plugins test
    command: /package-testing/scripts/ps_keyring_plugins_test/ps_keyring_plugins_test_81.sh ps81

  - name: Remove mysqld.my from /usr/sbin/
    file:
      path: /usr/sbin/mysqld.my
      state: absent

  - name: restart mysql service 
    command: systemctl restart mysql      
