# This task sets up local vault server for encryption test
#
  - name: Install needed deb packages for setting up vault
    apt:
      update_cache: no
      state: latest
      pkg:
       - unzip
       - wget
       - openssl
    when: ansible_os_family == "Debian"

  - name: Install needed rpm packages for setting up vault
    yum:
      state: latest
      name:
       - unzip
       - wget
       - openssl
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 8

  - name: Install needed rpm packages for setting up vault rhel 9
    yum:
      state: latest
      name:
       - unzip
       - wget
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 9

  - name: Download get_download_link.sh script
    get_url:
      url: https://raw.githubusercontent.com/kaushikpuneet07/percona-qa/fix-vault/get_download_link.sh
      dest: /package-testing/scripts/get_download_link.sh
      mode: 'a+rx'

  - name: Download vault_test_setup.sh script
    get_url:
      url: https://raw.githubusercontent.com/kaushikpuneet07/percona-qa/fix-vault/vault_test_setup.sh
      dest: /package-testing/scripts/vault_test_setup.sh
      mode: 'a+rx'

  - name: Setup local Vault server
    command: /package-testing/scripts/vault_test_setup.sh --use-ssl --workdir=/package-testing/scripts/vault-server
    args:
      chdir: /package-testing/scripts

  - name: Load data from VAULT_ADDR file
    slurp:
      src: /package-testing/scripts/vault-server/VAULT_ADDR
    register: vault_url_slurp

  - name: Set vault_url fact
    set_fact:
      vault_url: "{{ vault_url_slurp.content | b64decode | trim }}"

  - name: Load data from VAULT_TOKEN file
    slurp:
      src: /package-testing/scripts/vault-server/VAULT_TOKEN
    register: vault_token_slurp

  - name: Set vault_token fact
    set_fact:
      vault_token: "{{ vault_token_slurp.content | b64decode | trim }}"

  - name: Load data from VAULT_CERT file
    slurp:
      src: /package-testing/scripts/vault-server/VAULT_CERT
    register: vault_cert_slurp

  - name: Set vault_cert fact
    set_fact:
      vault_cert: "{{ vault_cert_slurp.content | b64decode | trim }}"

  - name: Set vault_location fact to local
    set_fact:
      vault_location: "local"
