centos-7:
  image: ami-0078de117bc1ba3b8
  user: centos
  subnet: subnet-085deaca8c1c59a4f
  aws_default_region: eu-central-1
  instance_type: t3.micro
debian-9:
  image: ami-006c08e13f35edce0
  user: admin
  subnet: subnet-085deaca8c1c59a4f
  aws_default_region: eu-central-1
  instance_type: t2.micro
debian-10:
  image: ami-0be88f8d647409e61
  user: admin
  subnet: subnet-085deaca8c1c59a4f
  aws_default_region: eu-central-1
  instance_type: t2.micro
ubuntu-18.04:
  image: ami-0a8561d8c5a4f098a
  user: ubuntu
  subnet: subnet-085deaca8c1c59a4f
  aws_default_region: eu-central-1
  instance_type: t2.micro
rhel8:
  image: ami-0badcc5b522737046
  user: ec2-user
  subnet: subnet-085deaca8c1c59a4f
  aws_default_region: eu-central-1
  instance_type: t2.micro