---
# This playbook does following:
#   enables Percona repository
#   installs Percona Platform for PostgreSQL packages
#   does some tests
#- name: include tasks for test env setup
#  include_tasks: ../../../tasks/test_prep.yml
#- name: include tasks for test env setup
#  include_tasks: ../test_prep.yml

# - name: include tasks for enabling main repo
#   include: ../tasks/enable_main_repo.yml
#   when: lookup('env', 'install_repo') == "main"

### temp part until percona-release is updated for PPG project

- name: Configure repository
  include_tasks: ../../common/tasks/enable_repo.yml

- name: Install vanila postgresql
  include_tasks: ../../common/tasks/install_pg12.yml

- name: Initialize Postgres RHEL
  command: /usr/pgsql-12/bin/postgresql-12-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Start Postgres RHEL
  service:
    name: postgresql-12
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Install ppg11 tools
  include_tasks: ../../common/tasks/install_ppg12_tools.yml
