  - name: Install percona repository package
    apt:
     deb: https://repo.percona.com/apt/pool/testing/p/percona-release/percona-release_1.0-25.generic_all.deb
    when: ansible_os_family == "Debian"

  - name: add the main Percona yum repos for centos 6 and 7
    yum: name=https://repo.percona.com/yum/testing/latest/RPMS/noarch/percona-release-1.0-25.noarch.rpm
    when: ansible_os_family == "RedHat"

  - name: clean and update yum cache
    shell: |
      yum clean all
      yum makecache
    when: ansible_os_family == "RedHat"

  - name: setup repo with percona-release
    command: percona-release setup {{ pg_version }}
    vars:
      pg_version: "{{ lookup('env', 'VERSION') }}"
