---
- name: Side Effect
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Stop pbm-agent service
      service:
        name: pbm-agent
        state: stopped

    - name: Install new PBM version (APT)
      apt:
        name: percona-backup-mongodb={{ lookup('env', 'VERSION') }}
        update_cache: yes
        state: latest
      when: ansible_os_family == "Debian"

    - name: Install new PBM version (YUM)
      yum:
        name: percona-backup-mongodb-{{ lookup('env', 'VERSION') }}
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Start pbm-agent service
      service:
        name: pbm-agent
        state: started
        enabled: yes
