---

- name: Configure repository
  include_tasks: ../../common/tasks/enable_repo.yml

- name: install Percona Platform for PostgreSQL 13 packages
  include_tasks: ../../../../tasks/install_ppg13.yml

- name: Initialize Postgres RHEL
  command: /usr/pgsql-13/bin/postgresql-13-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Start Postgres RHEL
  service:
    name: postgresql-13
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Install PPG tools
  include_tasks: ../../common/tasks/install_ppg13_tools.yml

- name: Install GCC Deb
  apt:
    name: gcc
  when: ansible_os_family == "Debian"

- name: Install GCC RHEL
  yum:
    name: gcc
  when: ansible_os_family == "RedHat"

- name: Create temporary directory for compilation
  command: mkdir /tmp/libpq_command_temp_dir

- name: Copy libpq source file
  copy:
    src: ../../common/files/lib_version.c
    dest: /tmp/libpq_command_temp_dir
