---
  - name: Fetch the vars from file
    ansible.builtin.include_vars: "{{ ENV_VAR_PATH }}"
  - set_fact:
      man_ip: "{{ PXC1_IP }}"
    when: 
    - "'pxc1' in inventory_hostname"

  - set_fact:
      man_ip: "{{ PXC2_IP }}"
    when: 
    - "'pxc2' in inventory_hostname"

  - set_fact:
      man_ip: "{{ PXC3_IP }}"
    when: 
    - "'pxc3' in inventory_hostname"

  - debug: var=man_ip

  - name: include tasks for test env setup
    include_tasks: ../../../../tasks/test_prep.yml

#
#  - name: include tasks for enabling test repo
#    include_tasks: ../../../../tasks/enable_pxc57_testing_repo.yml
#    when: lookup('env', 'install_repo') == "testing"  or lookup('env', 'install_repo') == ""

# default min_upgrade start with installation from main repo

  - name: include tasks for enabling main repo
    include_tasks: ../../../../tasks/enable_pxc57_main_repo.yml
    when: lookup('env', 'MIN_UPGRADE_TEST') == "PXC57_MAIN_TO_EOL_TESTING"

  - name: include tasks for enabling EOL repo
    include_tasks: ../../../../tasks/enable_pxc57_eol_tools_repo.yml
    when: lookup('env', 'MIN_UPGRADE_TEST') == "EOL_MAIN_TO_EOL_TESTING"

#  - name: include tasks for enabling experimental repo
#    include_tasks: ../../../../tasks/enable_pxc57_experimental_repo.yml
#    when: lookup('env', 'install_repo') == "experimental"

  - name: disable selinux
    selinux: state=disabled
    when: ansible_os_family == "RedHat"

  - name: flush iptables
    iptables:
      flush: yes
    when: (ansible_os_family == "RedHat") and (ansible_facts['distribution'] == "OracleLinux")

  - name: install PXC 5.7 new deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - percona-xtradb-cluster-full-57
      - percona-xtradb-cluster-57
      - percona-xtradb-cluster-source-5.7
    when: ansible_os_family == "Debian"
    environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"
      PERCONA_TELEMETRY_DISABLE: "1"

  - name: install python mysql deb packages for Debian Buster
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - python-mysqldb
    when: (ansible_os_family == "Debian") and (ansible_distribution_release == "buster")

  - name: install python mysql deb packages except Debian Buster
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - python3-mysqldb
    when: (ansible_os_family == "Debian") and (ansible_distribution_release != "buster")

  - name: install PXC 5.7 new rpm packages
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - Percona-XtraDB-Cluster-full-57
      - Percona-XtraDB-Cluster-57
    when: ansible_os_family == "RedHat"
    environment:
      PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"
      PERCONA_TELEMETRY_DISABLE: "1"

  - name: stop mysql service
    command: systemctl stop mysql

  - name: copy PXC config on centos 7
    template: src=../../../../templates/my_rpm_7.j2 dest=/etc/my.cnf
    when: ((ansible_os_family == "RedHat" and ansible_distribution_major_version >= "7")  or (ansible_distribution == "Amazon"))

  - name: copy PXC config on debian/ubuntu
    template: src=../../../../templates/my.j2
              dest=/etc/mysql/my.cnf
              mode=0640 owner=mysql group=root
    when: ansible_os_family == "Debian"

  - name: copy .my.cnf with credentials
    template: src=../../../../templates/my_57.j2
              dest=/root/.my.cnf
              mode=0640 owner=root group=root
    when: ansible_os_family == "RedHat"

  - name: start mysql service
    command: systemctl start mysql
    throttle: 1

  - name: register PXC version before min_upgrade
    shell: mysqld --version
    register: pxc_version

  - name: print PXC version before min_upgrade
    debug: var=pxc_version

  - name: check that PXC version is correct
    command: /package-testing/version_check.sh pxc57
    when: lookup('env', 'check_version') == "yes" or lookup('env', 'check_version') == ""

  - name: check that PXC package versions are correct
    command: /package-testing/package_check.sh pxc57
    when: lookup('env', 'check_version') == "yes" or lookup('env', 'check_version') == ""

  - name: run bats tests for mysql init scripts
    shell: sleep {{ sleep_before_tests | default('0') }}; /usr/local/bin/bats /package-testing/bats/pxc-init-scripts.bats
    throttle: 1

  - name: start mysql service
    command: systemctl start mysql
    throttle: 1

  - name: Check that the PXC Cluster is up and running
    shell: mysql -e "SHOW GLOBAL STATUS LIKE 'wsrep_cluster_size';" | awk '{print$2}' | sed -n '2 p' | grep '3'

