---
- name: Prepare Debian based
  hosts: all
  gather_facts: true
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: true
      changed_when: false
      when: ansible_os_family == "Debian" and ansible_distribution_release != "focal"

    - name: Install python for Ansible
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      become: true
      changed_when: false
      when: ansible_os_family == "Debian" and ansible_distribution_release == "focal"

- name: Prepare RHEL based
  hosts: all
  gather_facts: true
  tasks:
    - name: subscribe to RHSM
      become: true
      redhat_subscription:
        state: present
        username: "{{ lookup('env','RHEL_USER') }}"
        password: "{{ lookup('env','RHEL_PASS') }}"
        autosubscribe: true
        force_register: yes
      when: ansible_distribution == "RedHat"

    - name: Install python for Ansible RHEL
      raw: test -e /usr/bin/python || (yum update -y && yum install -y python2)
      become: true
      changed_when: false
      when: ansible_distribution == "RedHat"

#   - name: Install python for Ansible
#     raw: test -e /usr/bin/python || (yum update -y && yum install -y python-minimal)
#     become: true
#     changed_when: false
#     when: ansible_os_family != "RedHat"
