---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove Postgresql rpm packages
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-postgresql13
          - percona-postgresql-client-common
          - percona-postgresql-common
          - percona-postgresql-server-dev-all
          - percona-postgresql13
          - percona-postgresql13-contrib
          - percona-postgresql13-debuginfo
          - percona-postgresql13-devel
          - percona-postgresql13-docs
          - percona-postgresql13-libs
          - percona-postgresql13-llvmjit
          - percona-postgresql13-plperl
          - percona-postgresql13-plpython
          - percona-postgresql13-pltcl
          - percona-postgresql13-server
          - percona-postgresql13-test
          - percona-postgresql13-debuginfo
          - percona-postgresql13-debugsource
          - percona-postgresql13-devel-debuginfo
          - percona-postgresql13-libs-debuginfo
          - percona-postgresql13-plperl-debuginfo
          - percona-postgresql13-plpython3-debuginfo
          - percona-postgresql13-pltcl-debuginfo
          - percona-postgresql13-server-debuginfo
          - percona-postgresql13-test-debuginfo
      when: ansible_os_family == "RedHat"

    - name: remove pgaudit rpm packages
      yum:
        name: percona-pgaudit
        state: absent
      when: ansible_os_family == "RedHat"

    - name: remove pg_repack rpm packages
      yum:
        name: percona-pg_repack13
        state: absent
      when: ansible_os_family == "RedHat"

    - name: remove pgbackrest rpm packages
      yum:
        name: percona-pgbackrest
        state: absent
      when: ansible_os_family == "RedHat"

    - name: remove patroni rpm packages
      yum:
        name: percona-patroni
        state: absent
      when: ansible_os_family == "RedHat"
