---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove Postgresql rpm packages
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-postgresql12
          - percona-postgresql-client-common
          - percona-postgresql-common
          - percona-postgresql-server-dev-all
          - percona-postgresql12
          - percona-postgresql12-contrib
          - percona-postgresql12-debuginfo
          - percona-postgresql12-devel
          - percona-postgresql12-docs
          - percona-postgresql12-libs
          - percona-postgresql12-llvmjit
          - percona-postgresql12-plperl
          - percona-postgresql12-plpython
          - percona-postgresql12-pltcl
          - percona-postgresql12-server
          - percona-postgresql12-test
          - percona-postgresql12-debuginfo
          - percona-postgresql12-debugsource
          - percona-postgresql12-devel-debuginfo
          - percona-postgresql12-libs-debuginfo
          - percona-postgresql12-plperl-debuginfo
          - percona-postgresql12-plpython-debuginfo
          - percona-postgresql12-plpython3-debuginfo
          - percona-postgresql12-pltcl-debuginfo
          - percona-postgresql12-server-debuginfo
          - percona-postgresql12-test-debuginfo
      when: ansible_os_family == "RedHat"

    - name: remove pgaudit rpm packages
      yum:
        name: percona-pgaudit14_12
        state: absent
      when: ansible_os_family == "RedHat"

    - name: remove pg_repack rpm packages
      yum:
        name: percona-pg_repack12
        state: absent
      when: ansible_os_family == "RedHat"

    - name: remove pgbackrest rpm packages
      yum:
        name: percona-pgbackrest
        state: absent
      when: ansible_os_family == "RedHat"

    - name: remove patroni rpm packages
      yum:
        name: percona-patroni
        state: absent
      when: ansible_os_family == "RedHat"
