---
# This playbook does following:
#   enables Percona testing repository
#   installs latest version of proxysql
#   does some tests

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: include tasks for test env setup
    include: ../tasks/test_prep.yml

  - name: include tasks for enabling test repo
    include: ../tasks/enable_testing_repo.yml

  - name: install proxysql new deb packages
    apt: name={{item}} update_cache=yes state=latest
    with_items:
    - proxysql
    when: ansible_os_family == "Debian"

  - name: install proxysql new rpm packages
    yum: name={{item}} state=latest
    with_items:
    - proxysql
    when: ansible_os_family == "RedHat"

  - name: check that proxysql version is correct
    command: /package-testing/version_check.sh proxysql

  - name: start proxysql service
    service: name=proxysql state=started

  - name: stop proxysql service
    service: name=proxysql state=stopped

  - name: remove proxysql deb packages
    apt: name={{item}} state=absent
    with_items:
    - proxysql
    when: ansible_os_family == "Debian"

  - name: remove proxysql rpm packages
    yum: name={{item}} state=absent
    with_items:
    - proxysql
    when: ansible_os_family == "RedHat"
