---
# This playbook does the following:
#   enables Percona testing repository
#   installs latest version of PS 8.1, PyKmip and runs some tests

- hosts: all
  become: true
  become_method: sudo
  vars:
    PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"      

  tasks:
  - name: include tasks for test env setup
    include_tasks: ../tasks/test_prep.yml

  - name: disable selinux
    selinux: state=disabled
    when: ansible_os_family == "RedHat"

  - name: include tasks for enabling PS 8.1 test repo
    include: ../tasks/enable_ps81_main_repo.yml
    when: lookup('env', 'install_repo') == "main"

  - name: include tasks for enabling PS 8.1 test repo
    include: ../tasks/enable_ps81_testing_repo.yml
    when: lookup('env', 'install_repo') == "testing" or lookup('env', 'install_repo') == ""

  - name: include tasks for enabling PS 8.1 experimental repo
    include: ../tasks/enable_ps81_experimental_repo.yml
    when: lookup('env', 'install_repo') == "experimental"

  - name: download and extract world database
    command: "{{ item }}"
    with_items:
    - wget --no-check-certificate -P /package-testing https://raw.githubusercontent.com/Percona-QA/percona-qa/master/sample_db/world.sql

  - name: install Percona Server 8.1 packages
    include_tasks: ../tasks/install_ps81.yml

  - name: install sysbench new deb packages
    include_tasks: ../tasks/install_sysbench.yml
    when: lookup('env', 'install_repo') != "experimental"

  - name: list installed packages
    include_tasks: ../tasks/list_installed_packages.yml

  - name: stop mysql service
    service: name=mysql state=stopped

  - name: remove mysql data directory
    command: rm -r /var/lib/mysql

  - name: install python3-pip on RedHat/CentOS
    yum:
      name:
      - python3-pip
      state: latest
      update_cache: yes
    when: ansible_os_family == "RedHat"

  - name: install python3-pip on Debian/Ubuntu
    apt:
      name:
      - python3-pip
      state: latest
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: install pykmip
    command: "{{ item }}"
    with_items:
        - python3 -m pip install -U pip
        - python3 -m pip install -U setuptools
        - python3 -m pip install urllib3==1.26.6  
        - python3 -m pip install -U pykmip
    when: ansible_distribution_release != "bookworm"

  - name: install pykmip
    command: "{{ item }}"
    with_items:
        - python3 -m pip install -U --break-system-packages pip
        - python3 -m pip install -U --break-system-packages setuptools
        - python3 -m pip install -U --break-system-packages pykmip
    when: ansible_distribution_release == "bookworm"  

  - name: downgrade SQLAlchemy as new version doesn't work with pykmip
    command: pip3 install SQLAlchemy==1.4.46
    when: ansible_distribution_release != "bookworm"

  - name: downgrade SQLAlchemy as new version doesn't work with pykmip
    command: pip3 install --break-system-packages SQLAlchemy==1.4.46
    when: ansible_distribution_release == "bookworm"  

  - name: start pykmip server
    shell: nohup /usr/local/bin/pykmip-server -f /package-testing/kmip/server.conf -l /pykmip_server.log 2>&1 &

  - name: Check if kmip-server is running
    shell: ps -ef | grep kmip-server | grep -v grep

  - name: copy the global manifest for mysql
    copy:
        src: /package-testing/kmip/mysqld.my
        dest: /usr/sbin/
        remote_src: yes

  - name: copy the global configuration file for mysql in Redhat/CentOS
    copy:
        src: /package-testing/kmip/component_keyring_kmip.cnf
        dest: /usr/lib64/mysql/plugin/
        remote_src: yes
    when: ansible_os_family == "RedHat"

  - name: copy the global configuration file for mysql in Debian/Ubuntu
    copy:
        src: /package-testing/kmip/component_keyring_kmip.cnf
        dest: /usr/lib/mysql/plugin/
        remote_src: yes
    when: ansible_os_family == "Debian"

  - name: copy the encryption config file on Debian/Ubuntu
    copy:
        src: /package-testing/kmip/encryption.j2
        dest: /etc/mysql/conf.d/encryption.cnf
        remote_src: yes
    when: ansible_os_family == "Debian"

  - name: append include for RedHat
    lineinfile:
        path: /etc/my.cnf
        line: '!includedir /etc/my.cnf.d'
    when: ansible_os_family == "RedHat"

  - name: copy the encryption config file on RHEL/CentOS/Amazon
    copy:
        src: /package-testing/kmip/encryption.j2
        dest: /etc/my.cnf.d/encryption.cnf
        remote_src: yes
    when: ansible_os_family == "RedHat"

  - name: start mysql service
    service: name=mysql state=started

  - name: check mysql service status
    command: /package-testing/check_running.sh mysql running

  - name: set root password on centos
    command: /package-testing/setpass_57.sh
    when: ansible_os_family == "RedHat"

  - name: check that Percona Server package versions are correct
    command: /package-testing/package_check.sh ps81

  - name: import world database
    command: /package-testing/plugins_test_8.1.sh
