---
# This playbook does following:
#   enables Percona testing repository
#   installs latest version of PS 8.0, PT and PXB 8.0
#   does some tests

# Cosmic is still missing python 
- import_playbook: test_prep.yml

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: include tasks for test env setup
    include_tasks: ../tasks/test_prep.yml

  - name: include tasks for enabling main repo
    include: ../tasks/enable_main_repo.yml
    when: lookup('env', 'install_repo') == "main"

  - name: include tasks for enabling PS 8 test repo
    include: ../tasks/enable_ps8_main_repo.yml
    when: lookup('env', 'install_repo') == "main"

  - name: include tasks for enabling PS 8 test repo
    include: ../tasks/enable_ps8_testing_repo.yml
    when: lookup('env', 'install_repo') == "testing" or lookup('env', 'install_repo') == ""

  - name: include tasks for enabling test repo
    include: ../tasks/enable_testing_repo.yml
    when: lookup('env', 'install_repo') == "testing" or lookup('env', 'install_repo') == ""

  - name: include tasks for enabling PS 8 experimental repo
    include: ../tasks/enable_ps8_experimental_repo.yml
    when: lookup('env', 'install_repo') == "experimental"

  - name: download and extract world database
    command: "{{ item }}"
    with_items:
    - wget --no-check-certificate -P /package-testing https://raw.githubusercontent.com/Percona-QA/percona-qa/master/sample_db/world.sql

# - name: install Percona Toolkit new deb packages
#   include_tasks: ../tasks/install_pt.yml

# - name: disable the repo on RHEL8
#   command: dnf config-manager --set-disabled percona-rhel8-AppStream
#   when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: install Percona Server 8.0 packages
    include_tasks: ../tasks/install_ps80.yml

  - name: enable the repo on RHEL8
    command: dnf config-manager --set-enabled percona-rhel8-AppStream
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: include tasks for enabling tools experimental repo
    include: ../tasks/enable_tools_experimental_repo.yml
    when: lookup('env', 'install_repo') == "experimental"

  - name: install sysbench new deb packages
    include_tasks: ../tasks/install_sysbench.yml

  - name: install Percona XtraBackup 8.0 packages
    include_tasks: ../tasks/install_pxb80.yml

  - name: start mysql service with service command
    command: service mysql start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: start mysql service with systemctl command
    command: systemctl start mysql
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: set root password on centos
    command: /package-testing/setpass_57.sh
    when: ansible_os_family == "RedHat"

  - name: disable selinux on centos7 for TokuDB to work
    command: setenforce 0
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: install tokudb and restart server
    command: /usr/bin/ps-admin --enable-tokudb 

  - name: restart mysql service
    service: name=mysql state=restarted

  - name: re-run ps-admin to finish tokudb install
    command: /usr/bin/ps-admin --enable-tokudb 

# - name: check that Percona Server version is correct
#   command: /package-testing/version_check.sh ps80

# - name: check that Percona Server package versions are correct
#   command: /package-testing/package_check.sh ps80

  - name: keyring plugins test
    command: /package-testing/scripts/ps_keyring_plugins_test/ps_keyring_plugins_test.sh ps80

  - name: re-run ps_admin to install rocksdb
    command: /usr/bin/ps-admin --enable-rocksdb

  - name: install plugins, import world database, test tokudb
    command: /package-testing/plugins_test_80.sh ps

  - name: run some MyRocks tests
    command: /package-testing/scripts/ps_myrocks_test.sh

  - name: run mysql compression tests script
    command: /package-testing/scripts/mysql-comp-test/mysql_comp_test.sh ps80

  - name: run bats unit tests for ps-admin script
    command: /usr/local/bin/bats /package-testing/bats/ps-admin_unit.bats

  - name: run bats integration tests for ps-admin script
    command: /usr/local/bin/bats /package-testing/bats/ps-admin_integration.bats

  - name: run PAM tests
    include_tasks: ../tasks/pam_test.yml

  - name: install 3rd party packages with apt
    apt: 
      name: "{{ packages }}"
    vars:
      packages:
      - rsyslog-mysql
    when: ansible_os_family == "Debian"

  - name: install 3rd party packages with yum
    yum: 
      name: "{{ packages }}"
    vars:
      packages:
      - rsyslog-mysql
    when: ansible_os_family == "RedHat"

  - name: run bats tests for mysql init scripts
    command: /usr/local/bin/bats /package-testing/bats/mysql-init-scripts.bats

  - name: start mysql service
    service: name=mysql state=started

  - name: enable tools experimental for mysql-shell package
    command: percona-release enable tools testing

  - name: install mysql-shell package for CentOS
    yum: 
      name: "{{ packages }}"
    vars:
      packages:
      - percona-mysql-shell
    when: ansible_os_family == "RedHat" 

  - name: install mysql-shell package for Debian/Ubuntu
    apt:
      update_cache: yes 
      state: present
      name: "{{ packages }}"
    vars:
      packages:
      - percona-mysql-shell
    when: ansible_os_family == "Debian"

  - name: check that mysqladmin shutdown works correctly
    command: /package-testing/madmin_check.sh

  - name: remove Percona Server deb packages
    apt: 
      name: "{{ packages }}" 
      update_cache: no 
      state: absent
    vars:
      packages:
      - percona-server-server*
    when: ansible_os_family == "Debian"

  - name: remove Percona Server rpm packages
    yum: 
      name: "{{ packages }}"
      state: absent
    vars:
     packages:
      - percona-server-server*
    when: ansible_os_family == "RedHat"

  - name: check if process is stopped after package removal
    command: /package-testing/check_running.sh mysql stopped
