---
# This playbook does following:
#   sets main Percona repo
#   installs PSMDB 3.2
#   changes repo to testing
#   upgrades packages to the new version
#   does some tests

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: include tasks for test env setup
    include: ../tasks/test_prep.yml

#
# Install from main repository
#
  - name: include tasks for enabling main repo
    include: ../tasks/enable_main_repo.yml

  - name: install Percona Server for MongoDB 3.2 deb packages previous version
    apt: name={{item}} update_cache=yes state=latest
    with_items:
    - percona-server-mongodb-32
    - percona-server-mongodb-32-dbg
    when: ansible_os_family == "Debian"

  - name: install Percona Server for MongoDB 3.2 new rpm packages previous version
    yum: name={{item}} state=latest
    with_items:
    - Percona-Server-MongoDB-32
    - Percona-Server-MongoDB-32-debuginfo
    when: ansible_os_family == "RedHat"

  - name: start mongod with service
    command: service mongod start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: start mongod with systemctl
    command: systemctl start mongod
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

#
# Enable testing repository
#
  - include: ../tasks/enable_testing_repo.yml

#
# Upgrade packages
#
  - name: upgrade Percona Server for MongoDB 3.2 to new deb packages
    apt: name={{item}} update_cache=yes state=latest
    with_items:
    - percona-server-mongodb-32
    - percona-server-mongodb-32-server
    - percona-server-mongodb-32-mongos
    - percona-server-mongodb-32-shell
    - percona-server-mongodb-32-tools
    - percona-server-mongodb-32-dbg
    when: ansible_os_family == "Debian"

  - name: upgrade Percona Server for MongoDB 3.2 to new rpm packages
    yum: name={{item}} state=latest
    with_items:
    - Percona-Server-MongoDB-32
    - Percona-Server-MongoDB-32-server
    - Percona-Server-MongoDB-32-shell
    - Percona-Server-MongoDB-32-mongos
    - Percona-Server-MongoDB-32-tools
    - Percona-Server-MongoDB-32-debuginfo
    when: ansible_os_family == "RedHat"

  - name: check that PSMDB 3.2 package versions are correct
    command: /package-testing/package_check.sh psmdb32

  - name: test SE change, import data, restart service
    command: /package-testing/psmdb_test.sh 3.2

  - name: set pass and enable auth
    command: /package-testing/scripts/psmdb_set_auth.sh

  - name: run bats tests for mongo init scripts
    command: /usr/local/bin/bats /package-testing/bats/mongo-init-scripts.bats

  - name: start mongod service
    service: name=mongod state=started

  - name: remove Percona Server for MongoDB 3.2 deb packages
    apt: name={{item}} update_cache=no state=absent
    with_items:
    - percona-server-mongodb-32-server
    when: ansible_os_family == "Debian"

  - name: remove Percona Server for MongoDB 3.2 rpm packages
    yum: name={{item}} state=absent
    with_items:
    - Percona-Server-MongoDB-32-server
    when: ansible_os_family == "RedHat"

  - name: check if process is stopped after package removal
    command: /package-testing/check_running.sh mongodb stopped
