---
# This playbook does following:
#   * sets main Percona repo
#   * installs PSMDB 3.6
#   * inserts some data
#   * changes repo to testing
#   * uninstalls PSMDB 3.6 and installs 4.0
#   * does some tests

- import_playbook: test_prep.yml

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: include tasks for test env setup
    include_tasks: ../tasks/test_prep.yml

#
# Install from main repository
#
  - name: include tasks for enabling main repo
    include_tasks: ../tasks/enable_psmdb_repo.yml
    vars:
      psmdb_repo: "original"

  - name: install Percona Server for MongoDB 3.6 deb packages previous version
    include_tasks: ../tasks/install_psmdb_36.yml

  - name: start mongod with service
    command: service mongod start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: start mongod with systemctl
    command: systemctl start mongod
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int > 6

  - name: insert some data
    command: /package-testing/scripts/mongo_insert.sh

  - name: check that data is there
    command: /package-testing/scripts/mongo_check.sh

  - name: remove Percona Server for MongoDB 3.6 deb packages
    apt:
      name: "{{ packages }}"
      update_cache: no
      state: absent
    vars:
      packages:
      - percona-server-mongodb-36-server
      - percona-server-mongodb-36-dbg
    when: ansible_os_family == "Debian"

  - name: remove Percona Server for MongoDB 3.6 rpm packages
    yum:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - Percona-Server-MongoDB-36-server
      - Percona-Server-MongoDB-36
      - Percona-Server-MongoDB-36-shell
      - Percona-Server-MongoDB-36-mongos
      - Percona-Server-MongoDB-36-tools
      - Percona-Server-MongoDB-36-debuginfo
      - Percona-Server-MongoDB-36-debugsource
      - Percona-Server-MongoDB-36-mongos-debuginfo
      - Percona-Server-MongoDB-36-server-debuginfo
      - Percona-Server-MongoDB-36-shell-debuginfo
      - Percona-Server-MongoDB-36-tools-debuginfo
    when: ansible_os_family == "RedHat"

#
# Enable testing repository
#
  - name: include tasks for enabling test repo
    include_tasks: ../tasks/enable_psmdb_repo.yml
    vars:
      psmdb_repo: "psmdb-40 testing"

#
# Upgrade packages
#
  - name: upgrade to Percona Server for MongoDB 4.0 new deb packages
    include_tasks: ../tasks/install_psmdb.yml

  - name: start mongod service
    service: name=mongod state=started

  - name: check that PSMDB 4.0 package versions are correct
    command: /package-testing/package_check.sh psmdb40

  - name: check that PSMDB 4.0 version is correct
    command: /package-testing/version_check.sh psmdb40

  - name: check that data is still there after upgrade
    command: /package-testing/scripts/mongo_check.sh

  - name: test SE change, import data, restart service
    command: /package-testing/scripts/psmdb_test.sh 4.0

  - name: run bats tests for mongo init scripts
    command: /usr/local/bin/bats /package-testing/bats/mongo-init-scripts.bats

  - name: start mongod service
    service: name=mongod state=started

  - name: remove Percona Server for MongoDB 4.0 deb packages
    apt:
      name: "{{ packages }}"
      update_cache: no
      state: absent
    vars:
      packages:
      - percona-server-mongodb-server
    when: ansible_os_family == "Debian"

  - name: remove Percona Server for MongoDB 4.0 rpm packages
    yum:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - percona-server-mongodb-server
    when: ansible_os_family == "RedHat"

  - name: check if process is stopped after package removal
    command: /package-testing/check_running.sh mongodb stopped
