---
# This playbook does following:
#   * sets main Percona repo
#   * installs PSMDB 3.2 
#   * inserts some data
#   * changes repo to testing
#   * uninstalls PSMDB 3.2 and installs 3.4
#   * does some tests

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: include tasks for test env setup
    include_tasks: ../tasks/test_prep.yml

#
# Install from main repository
#
  - name: include tasks for enabling main repo
    include_tasks: ../tasks/enable_main_repo.yml

  - name: install Percona Server for MongoDB 3.2 deb packages previous version
    apt: name={{item}} update_cache=yes state=latest
    with_items:
    - percona-server-mongodb-32
    - percona-server-mongodb-32-dbg
    when: ansible_os_family == "Debian"

  - name: install Percona Server for MongoDB 3.2 new rpm packages previous version
    yum: name={{item}} state=latest
    with_items:
    - Percona-Server-MongoDB-32
    - Percona-Server-MongoDB-32-debuginfo
    when: ansible_os_family == "RedHat"

  - name: start mongod with service
    command: service mongod start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: start mongod with systemctl
    command: systemctl start mongod
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: insert some data
    command: /package-testing/scripts/mongo_insert.sh

  - name: check that data is there
    command: /package-testing/scripts/mongo_check.sh

  - name: remove Percona Server for MongoDB 3.2 deb packages
    apt: name={{item}} update_cache=no state=absent
    with_items:
    - percona-server-mongodb-32-server
    when: ansible_os_family == "Debian"

  - name: remove Percona Server for MongoDB 3.2 rpm packages
    yum: name={{item}} state=absent
    with_items:
    - Percona-Server-MongoDB-32-server
    when: ansible_os_family == "RedHat"

#
# Enable testing repository
#
  - include: ../tasks/enable_testing_repo.yml

#
# Upgrade packages
#
  - name: upgrade Percona Server for MongoDB 3.4 to new deb packages
    apt: name={{item}} update_cache=yes state=latest
    with_items:
    - percona-server-mongodb-34
    - percona-server-mongodb-34-server
    - percona-server-mongodb-34-mongos
    - percona-server-mongodb-34-shell
    - percona-server-mongodb-34-tools
    - percona-server-mongodb-34-dbg
    when: ansible_os_family == "Debian"

  - name: upgrade Percona Server for MongoDB 3.4 to new rpm packages
    yum: name={{item}} state=latest
    with_items:
    - Percona-Server-MongoDB-34
    - Percona-Server-MongoDB-34-server
    - Percona-Server-MongoDB-34-shell
    - Percona-Server-MongoDB-34-mongos
    - Percona-Server-MongoDB-34-tools
    - Percona-Server-MongoDB-34-debuginfo
    when: ansible_os_family == "RedHat"

  - name: check that PSMDB 3.4 package versions are correct
    command: /package-testing/package_check.sh psmdb34

  - name: test SE change, import data, restart service
    command: /package-testing/psmdb_test.sh 3.4

  - name: check that data is still there after upgrade
    command: /package-testing/scripts/mongo_check.sh

  - name: run bats tests for mongo init scripts
    command: /usr/local/bin/bats /package-testing/bats/mongo-init-scripts.bats

  - name: start mongod service
    service: name=mongod state=started

  - name: remove Percona Server for MongoDB 3.4 deb packages
    apt: name={{item}} update_cache=no state=absent
    with_items:
    - percona-server-mongodb-34-server
    when: ansible_os_family == "Debian"

  - name: remove Percona Server for MongoDB 3.4 rpm packages
    yum: name={{item}} state=absent
    with_items:
    - Percona-Server-MongoDB-34-server
    when: ansible_os_family == "RedHat"

  - name: check if process is stopped after package removal
    command: /package-testing/check_running.sh mongodb stopped
