---
# This playbook does following:
#   * sets main Percona repo
#   * installs PSMDB 4.2
#   * inserts some data
#   * changes repo to testing
#   * uninstalls PSMDB 4.2 and installs 4.4
#   * does some tests

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: install GPG key for epel 8
    rpm_key:
     state: present
     key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: install GPG key for Percona repos
    rpm_key:
     state: present
     key: https://repo.percona.com/yum/RPM-GPG-KEY-Percona

  - name: include tasks for test env setup
    include_tasks: ../tasks/test_prep.yml

  - name: include tasks for enabling test repo
    include_tasks: ../tasks/enable_psmdb_repo.yml
    vars:
      psmdb_repo: "psmdb-42 testing"
    when: lookup('env', 'install_repo') == "testing" or lookup('env', 'install_repo') == ""

  - name: include tasks for enabling main repo
    include_tasks: ../tasks/enable_psmdb_repo.yml
    vars:
      psmdb_repo: "psmdb-42"
    when: lookup('env', 'install_repo') == "main"

  - name: include tasks for enabling experimental repo
    include_tasks: ../tasks/enable_psmdb_repo.yml
    vars:
      psmdb_repo: "psmdb-42 experimental"
    when: lookup('env', 'install_repo') == "experimental"

  - name: install PSMDB packages
    include_tasks: ../tasks/install_psmdb.yml

  - name: start mongod with service
    command: service mongod start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: start mongod with systemctl
    command: systemctl start mongod
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version > "6"

  - name: check that PSMDB 4.2 package versions are correct
    command: /package-testing/package_check.sh psmdb42

  - name: check that PSMDB 4.2 version is correct
    command: /package-testing/version_check.sh psmdb42

  - name: insert some data
    command: /package-testing/scripts/mongo_insert.sh

  - name: check that data is there
    command: /package-testing/scripts/mongo_check.sh

  - name: remove Percona Server for MongoDB 4.2 packages
    include_tasks: ../tasks/remove_psmdb.yml

#
# Upgrade packages
#

  - name: include tasks for enabling testing PSMDB 4.4 repo
    include_tasks: ../tasks/enable_psmdb_repo.yml
    vars:
      psmdb_repo: "psmdb-44 testing"

  - name: upgrade Percona Server for MongoDB to 4.4 packages
    include_tasks: ../tasks/install_psmdb.yml

  - name: check that PSMDB 4.4 package versions are correct
    command: /package-testing/package_check.sh psmdb44

  - name: check that PSMDB 4.4 version is correct
    command: /package-testing/version_check.sh psmdb44

  - name: run bats tests for mongo init scripts
    command: /usr/local/bin/bats /package-testing/bats/mongo-init-scripts.bats

  - name: start mongod service
    service: name=mongod state=started

  - name: check that data is still there after upgrade
    command: /package-testing/scripts/mongo_check.sh

  - name: test SE change, import data, restart service
    command: /package-testing/scripts/psmdb_test.sh 4.4

  - name: remove Percona Server for MongoDB 4.4 deb packages
    apt: name={{item}} update_cache=no state=absent
    with_items:
    - percona-server-mongodb-server
    when: ansible_os_family == "Debian"

  - name: remove Percona Server for MongoDB 4.4 rpm packages
    yum: name={{item}} state=absent
    with_items:
    - percona-server-mongodb-server
    when: ansible_os_family == "RedHat"

  - name: check if process is stopped after package removal
    command: /package-testing/check_running.sh mongodb stopped
