---
# This playbook sets up the first PXC node from percona repo

- hosts: all

  tasks:
  - name: add the repo
    apt_repository: repo='deb [arch=amd64] http://192.168.5.9/apt {{ansible_lsb.codename}} main' state=present
#    apt_repository: repo='deb http://repo.percona.com/apt {{ansible_lsb.codename}} main' state=present
    sudo: yes
  # Add an Apt signing key, will not download if present
  - apt_key: id=CD2EFD2A keyserver=keys.gnupg.net state=present
    sudo: yes
#  - name: pin the percona repo for trusty
#    copy: src=/home/hrvoje/worktable/percona-cluster/00percona.pref dest=/etc/apt/preferences.d/
#    sudo: yes
  - name: install vim, pv, python-mysqldb, and PXC-5.5
    apt: name={{item}} update_cache=yes
    with_items:
    - vim
    - pv
    - percona-xtradb-cluster-galera-2.x
    - percona-xtradb-cluster-full-55
    - python-mysqldb
    sudo: yes
  # stop mysql service
  - service: name=mysql pattern=/usr/bin/mysqld_safe state=stopped 
    sudo: yes
  - name: configure PXC
    template: src=/home/hrvoje/worktable/percona-cluster/templates/my.j2 
              dest=/etc/mysql/my.cnf
              mode=0640 owner=mysql group=root
    sudo: yes
  #bootstrap the cluster
  - command: service mysql bootstrap-pxc
    sudo: yes
  #add sstuser
  - mysql_user: name=sstuser password=s3cretPass priv=*.*:RELOAD,"LOCK TABLES","REPLICATION CLIENT" state=present
    sudo: yes
  - name: copy sample db
    sudo: yes
    copy: src=/home/hrvoje/worktable/sampledbs/world_innodb.sql dest=/home/vagrant/
  - name: copy sample db
    sudo: yes
    copy: src=/home/hrvoje/worktable/sampledbs/world_innodb.sql dest=/home/vagrant/
  - name: copy plugin_test
    sudo: yes
    copy: src=/home/hrvoje/worktable/percona-cluster/plugins_test_55.sh dest=/home/vagrant/
  - name: copy version_check
    sudo: yes
    copy: src=/home/hrvoje/worktable/percona-cluster/version_check.sh dest=/home/vagrant/
