---
# This playbook sets up the pxc

- hosts: all

  tasks:
  - name: add the repo
    apt_repository: repo='deb [arch=amd64] http://192.168.5.9/apt {{ansible_lsb.codename}} main testing' state=present
#    apt_repository: repo='deb http://repo.percona.com/apt {{ansible_lsb.codename}} main testing' state=present
    sudo: yes
  # Add an Apt signing key, will not download if present
  - apt_key: id=CD2EFD2A keyserver=keys.gnupg.net state=present
    sudo: yes
  - name: install galera, vim, pv, python-mysqldb, pxc-55
    apt: name={{ item }} update_cache=yes
    with_items: 
    - percona-xtradb-cluster-galera-2.x
    - vim
    - pv
    - python-mysqldb
    - percona-xtradb-cluster-55
    sudo: yes
  - name: copy sample db
    sudo: yes
    copy: src=/home/hrvoje/worktable/sampledbs/world_innodb.sql dest=/home/vagrant/
  - name: copy plugin_test
    sudo: yes
    copy: src=/home/hrvoje/worktable/percona-cluster/plugins_test_55.sh dest=/home/vagrant/
  - name: copy version_check
    sudo: yes
    copy: src=/home/hrvoje/worktable/percona-cluster/version_check.sh dest=/home/vagrant/
  # stop mysql service
  - service: name=mysql pattern=/usr/bin/mysqld_safe state=stopped 
    sudo: yes
  - name: configure PXC
    template: src=/home/hrvoje/worktable/percona-cluster/templates/my.j2 
              dest=/etc/mysql/my.cnf
              mode=0640 owner=mysql group=root
    sudo: yes
  # start mysql service
  - command: service mysql start
    sudo: yes
  
